version: "3"
services:
  signal-bot-0:
    image: signal-bot
    depends_on:
      - signal-cli-rest-api-0
    environment:
      - SIGNAL_BOT_ID=0
      - USER_NUMBER=<PHONE NUMBER>

  signal-bot-1:
    image: signal-bot
    depends_on:
      - signal-cli-rest-api-1
    environment:
      - SIGNAL_BOT_ID=1
      - USER_NUMBER=<PHONE NUMBER>

  signal-bot-2:
    image: signal-bot
    depends_on:
      - signal-cli-rest-api-2
    environment:
      - SIGNAL_BOT_ID=2
      - USER_NUMBER=<PHONE NUMBER>

  signal-cli-rest-api-0:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "./signal-cli-config-0:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
    restart: unless-stopped

  signal-cli-rest-api-1:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8081:8080" #map docker port 8080 to host port 8081.
    volumes:
      - "./signal-cli-config-1:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
    restart: unless-stopped

  signal-cli-rest-api-2:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8082:8080" #map docker port 8080 to host port 8082.
    volumes:
      - "./signal-cli-config-2:/home/.local/share/signal-cli-2" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
    restart: unless-stopped